# Generated by Django 3.1.2 on 2023-12-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16, verbose_name='用户名')),
                ('phone', models.CharField(max_length=16, verbose_name='手机号')),
                ('remain_power', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='剩余电量')),
                ('a1', models.BinaryField(max_length=1024, verbose_name='SK_A1')),
                ('a2', models.BinaryField(max_length=1024, verbose_name='SK_A2')),
                ('b1', models.BinaryField(max_length=1024, verbose_name='PK_A1(bytes)')),
                ('sb1', models.CharField(max_length=1024, verbose_name='PK_A1(string)')),
                ('b2', models.BinaryField(max_length=1024, verbose_name='PK_A2(bytes)')),
                ('sb2', models.CharField(max_length=1024, verbose_name='PK_A2(string)')),
                ('priority', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='优先级')),
            ],
        ),
        migrations.CreateModel(
            name='Gsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.BinaryField(max_length=1024, verbose_name='生成元')),
                ('sk_s', models.BinaryField(max_length=1024, verbose_name='服务器私钥')),
                ('pk_s', models.BinaryField(max_length=1024, verbose_name='服务器公钥(bytes)')),
                ('spk_s', models.CharField(max_length=1024, verbose_name='服务器公钥(string)')),
                ('sk_B1', models.BinaryField(max_length=1024, verbose_name='MGCC私钥1')),
                ('pk_B1', models.BinaryField(max_length=1024, verbose_name='MGCC公钥1(bytes)')),
                ('spk_B1', models.CharField(max_length=1024, verbose_name='MGCC公钥1(string)')),
                ('sk_B2', models.BinaryField(max_length=1024, verbose_name='MGCC私钥2')),
                ('pk_B2', models.BinaryField(max_length=1024, verbose_name='MGCC公钥2(bytes)')),
                ('spk_B2', models.CharField(max_length=1024, verbose_name='MGCC公钥2(string)')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True, verbose_name='调度轮数')),
                ('suppliers', models.CharField(max_length=1024, verbose_name='供电用户名单')),
                ('demanders', models.CharField(max_length=1024, verbose_name='需电用户名单')),
                ('supply', models.CharField(max_length=1024, verbose_name='实际供电结果')),
                ('demand', models.CharField(max_length=1024, verbose_name='实际得电结果')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('create_time', models.DateField(verbose_name='入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Trapdoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0, verbose_name='调度轮数')),
                ('keyword', models.CharField(max_length=16, verbose_name='关键字')),
                ('st', models.BinaryField(max_length=1024, verbose_name='陷门')),
                ('trapdoor_time', models.DateTimeField(auto_now_add=True, verbose_name='调度时间')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.consumers')),
            ],
        ),
        migrations.CreateModel(
            name='IC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=16, verbose_name='关键字')),
                ('ic1', models.BinaryField(max_length=1024, verbose_name='ic1')),
                ('ic2', models.BinaryField(max_length=1024, verbose_name='ic2')),
                ('power', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='能源量')),
                ('user_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('type', models.SmallIntegerField(choices=[(1, '供电'), (0, '需电')], default=0, verbose_name='类型')),
                ('index', models.IntegerField(verbose_name='调度轮数')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.consumers')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trapdoor',
            constraint=models.UniqueConstraint(fields=('index', 'userid'), name='uc_index_userid'),
        ),
        migrations.AddConstraint(
            model_name='ic',
            constraint=models.UniqueConstraint(fields=('userid', 'index'), name='uc_userid_index'),
        ),
    ]
